service: gladnews

frameworkVersion: ">=1.9.0 <2.0.0"

plugins:
  - serverless-s3bucket-sync

custom:
  stage: ${opt:stage, self:provider.stage}
  dev:
    DynamoCapacity:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
  prod:
    DynamoCapacity:
      ReadCapacityUnits: 5
      WriteCapacityUnits: 5

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  memorySize: 256
  timeout: 10s
  environment:
    SLS_STAGE: ${self:custom.stage}
    DDB_TABLE: {Ref: LinkDB}
  iamRoleStatements:
    - Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
        "Fn::Join":
          - ""
          -
            - "arn:aws:dynamodb:"
            - Ref: "AWS::Region"
            - ":"
            - Ref: "AWS::AccountId"
            - ":table/"
            - Ref: LinkDB
      Effect: Allow

functions:
  main:
    handler: main/index.handler
    events:
      - http:
          path: /
          method: get

resources:
  Outputs:
    WebSiteUrl:
      Value: {"Fn::GetAtt": [WebSite, WebsiteURL]}
    WebSiteBucket:
      Value: {Ref: WebSite}
  Resources:
    WebSite:
      Type: "AWS::S3::Bucket"
      Properties:
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
    LinkDB:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: slug
            AttributeType: S
        KeySchema:
          - AttributeName: slug
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.${self:custom.stage}.DynamoCapacity.ReadCapacityUnits}
          WriteCapacityUnits: ${self:custom.${self:custom.stage}.DynamoCapacity.WriteCapacityUnits}
    Users:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: ${self:service}-${self:custom.stage}
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
          UnusedAccountValidityDays: 7
        AliasAttributes:
          - preferred_username
        MfaConfiguration: "OFF"
        Policies:
          MinimumLength: 6
          RequireLowercase: true        
          RequireNumbers: false
          RequireSymboms: false
          RequireUppercase: true        
        Schema:
          - Name: email
            AttributeDataType: String
            Required: true
          - Name: name
            AttributeDataType: String
            Required: true
